### ISSUE TITLE
Unable to run Application, It seems data component missing from Repository

### ISSUE THREAD

**Issue by Raghuram143403** [pranjalkv/Tractv_movie_app#1]
[plugin:vite:import-analysis] Failed to resolve import "./components/data" from "src/App.jsx". Does the file exist?
/home/local/CORP/rannapaneni/TMDB-Projects/Tractv_movie_app-main/src/App.jsx:3:17
10 |  import './App.css';
11 |  import Navbar from './components/Navbar';
12 |  import list from './components/data';
   |                    ^
13 |  import Error from './components/Error';
14 |  import Loading from './components/Loading';

**Comment by pranjalkv** [comment]
yes it will not run because i have removed Api Key from data.jsx files you need get your own Api key ,also you need to get genre and lang data locally or from api call

**Comment by Raghuram143403** [comment]
Yes we can use our API key but app is looking for list to load app, in code
we have lot of dependency on list for fetch.

**Comment by pranjalkv** [comment]
Yes all data to be called with APikey is stored in an object name list inside a folder name data.jsx like this let list={
getBanner: `https://api.themoviedb.org/3/trending/all/week?${API_KEY}&language=en-US`,
getNetflix: `https://api.themoviedb.org/3/discover/tv?${API_KEY}&with_networks=213`,
}
export default list
